version: 2
updates:
  - package-ecosystem: "github-actions"
    cooldown:
      default-days: 7
    commit-message:
      prefix: "chore"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    cooldown:
      default-days: 7
    commit-message:
      prefix: "chore"
    directory: "/"
    schedule:
      interval: "weekly"
